version: "3.9"
services:
  client:
    image: client-vite
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_SERVER_URL=http://localhost:3000
    command: ["npm", "run", "dev"]
    networks:
      - frontend

  server:
    image: server-node
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - JWT_KEY=(*%*(&(#)^(&*%#&^@)KrutibashChatAppTalkative080125))
      - ORIGIN=http://localhost:5173
      - DATABASE_URL=mongodb://mongo:27017/talkative
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  frontend:
  backend:
